<?php

namespace NasaBundle\ORM;

use NasaBundle\Entity\NearEarthObject;
use NasaBundle\Filter\PostFilter;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * PostRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class NearEarthObjectRepository extends EntityRepository
{
    public function findByFilter(PostFilter $filter)
    {
        $builder = $this->getEntityManager()->createQueryBuilder();
        $alias   = 'p';
        $qb = $builder->select($alias)->from(Post::class, $alias)
        ->join(NearEarthObject::class, 'c', Join::WITH, 'p.category = c')
        ;
        if ($filter->hasAuthor()) {
            $qb->andWhere('p.author = :author');
            $qb->setParameter('author', $filter->getAuthor());
        }
        if ($filter->hasCategories()) {
            $qb->andWhere('c.id IN(:categories)');
            $qb->setParameter('categories', $filter->getCategories());
        }
        if ($filter->hasFrom()) {
            $qb->andWhere('p.created >= :from');
            $qb->setParameter('from', $filter->getFrom());
        }
        if ($filter->hasTo()) {
            $qb->andWhere('p.created >= :to');
            $qb->setParameter('to', $filter->getTo());
        }


        return $qb->getQuery()->getResult();
    }
}
